(() => {
 'use strict';
 const $=id=>document.getElementById(id),app=$('spm-app');
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names={bm:['国文','Bahasa Melayu','Aa'],english:['英文','English','En'],chinese:['华文','Bahasa Cina','文'],math:['数学','Matematik','∑'],science:['科学','Sains','⚗'],history:['历史','Sejarah','时'],moral:['道德','Pendidikan Moral','心'],addmath:['附加数学','Matematik Tambahan','ƒ'],physics:['物理','Fizik','力'],chemistry:['化学','Kimia','H₂'],biology:['生物','Biologi','叶'],accounting:['会计','Prinsip Perakaunan','账'],economics:['经济','Ekonomi','↗'],business:['商科','Perniagaan','企'],geography:['地理','Geografi','◎'],art:['美术','Pendidikan Seni Visual','◈']};
 let data,questions=new Map(),tasks=new Map(),chapters=new Map(),subject='',tab='chapters',level='F4',language='both',attempt=null,view='home',actor='guest',toastTimer,ready=false;
 const storeKey=()=>`wordquest.spm.v1.${actor}`;
 const title=x=>typeof x==='string'?x:(x?.zh||x?.bm||x?.en||'');
 function text(x){if(typeof x==='string')return esc(x);if(!x)return '';const langs=language==='en'?['en','bm','zh']:language==='bm'?['bm','en','zh']:['bm','en','zh'];const keys=langs.filter(k=>typeof x[k]==='string'&&x[k].trim());return keys.slice(0,language==='both'?2:1).map((k,i)=>`<span class="text ${i?'tx-alt':''}" lang="${k==='bm'?'ms':k==='zh'?'zh-Hans':'en'}">${esc(x[k])}</span>`).join('');}
 function notify(message){$('status').textContent=message;$('status').classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').classList.remove('on'),5000);}
 function show(html,focus=true){app.innerHTML=html;if(focus){const h=app.querySelector('h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo(0,0);}}
 function persist(){if(!attempt)return;try{sessionStorage.setItem(storeKey(),JSON.stringify(attempt));}catch{notify('浏览器无法保存进度，请下载备份后再离开。');}}
 function valid(a){if(!a||typeof a.title!=='string'||a.title.length>500||a.version!==1||a.revision!==data.revision||!Array.isArray(a.items)||!a.items.length||a.items.length>200||!a.items.every(i=>i&&((i.type==='q'&&questions.has(i.id))||(i.type==='t'&&tasks.has(i.id)))))return false;if(new Set(a.items.map(i=>i.type+':'+i.id)).size!==a.items.length)return false;if(!a.responses||typeof a.responses!=='object'||!Number.isInteger(a.index)||a.index<0||a.index>=a.items.length||typeof a.finished!=='boolean')return false;if(!Number.isFinite(a.started)||a.started<=0||!Number.isFinite(a.durationMinutes)||a.durationMinutes<1||a.durationMinutes>240||!['timed','study'].includes(a.mode))return false;if(a.mode==='timed'&&(!Number.isFinite(a.deadline)||a.deadline!==a.started+a.durationMinutes*60000))return false;return a.items.every(i=>{const v=a.responses[i.id];return v===undefined||(i.type==='q'?Number.isInteger(v)&&v>=0&&v<=3:typeof v==='string'&&v.length<=12000);});}
 function rawSaved(){try{return sessionStorage.getItem(storeKey());}catch{return null;}}
 function readSaved(){try{const a=JSON.parse(rawSaved()||'null');if(valid(a)){a.selfMarks=cleanMarks(a.selfMarks);return a;}return null;}catch{return null;}}
 function savedNotice(){const a=readSaved();if(a)return `<div class="notice row spread"><div><strong>${a.finished?'上次的练习结果':'有一份练习尚未完成'}</strong><br><span class="small">${esc(a.title)}${!a.finished&&a.mode==='timed'?' · 计时继续运行，过时将自动交卷':''}</span></div><button class="btn secondary" data-act="resume">${a.finished?'查看结果':'继续练习'}</button></div>`;if(rawSaved())return `<div class="notice row spread"><div><strong>题库已更新，或旧进度格式不兼容</strong><p class="small">旧作答仍保存在本标签页。题目与选项版本可能已变化，不能继续评分；请先下载旧进度备份保留答案。开始新练习将替换这份旧进度。</p></div><button class="btn secondary" data-act="export-old">下载旧进度备份</button></div>`;return '';}
 function home(){view='home';subject='';show(`<section class="hero"><div><span class="eyebrow">FORM 4 · FORM 5 · SPM</span><h1>把知识，写成答案。</h1><p>按章节查漏补缺，再用综合练习检验自己。交卷后核对选择题；写作、推理和作品用评分要点逐项检查。</p><div class="row"><span class="badge">${data.courses.length} 门年级课程</span><span class="badge">${questions.size} 道选择题</span><span class="badge">${tasks.size} 项构答与实作</span></div></div><aside class="hero-note"><span class="eyebrow">YOUR NEXT STEP</span><p><strong>先练会，再限时。</strong></p><p>每科 5 套原创短版综合练习，附解析与参考评分。各套共享题库，部分题目重复。</p></aside></section>${savedNotice()}<div class="row spread"><h2>选择一科，开始学习</h2><span class="small">核心科 + 常用选修科</span></div><div class="grid">${Object.entries(names).filter(([k])=>data.courses.some(c=>c.subject===k)).map(([key,n])=>`<button class="subject" data-subject="${key}"><span class="symbol" aria-hidden="true">${n[2]}</span><h3>${n[0]}</h3><span>${n[1]}</span><small>Form 4 / Form 5 · 章节 / 综合练习 ↗</small></button>`).join('')}</div><section class="panel"><h2>怎样使用这间学习室</h2><p>章节练习包含已列章题的基础样本。综合练习是原创短版，并非官方完整模拟试卷；当前题量也不表示已覆盖每项学习标准。</p><p class="small">进度自动保存在本标签页。关闭前可下载备份，之后导入继续。选择题诊断成绩与构答自评分别显示，不换算 SPM 等级或游戏奖励。</p><div class="row"><button class="btn light" data-act="import">导入练习备份</button><a href="./curriculum-audit.html">查看课程覆盖与来源 →</a></div></section>`);}
 function sourcesHtml(ids){return `<ul class="source-list">${[...new Set(ids)].map(id=>data.sources.find(s=>s.id===id)).filter(Boolean).map(s=>`<li><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title||s.name||s.id)}</a>${s.authority?`<br><span class="muted">${esc(s.authority)}</span>`:''}</li>`).join('')}</ul>`;}
 function formatHtml(){const f=data.examFormats.find(f=>f.subject===subject);if(!f)return '<p>请查看下方 LP／课程来源及学校当年考试通知。练习时长是本网站短版安排。</p>'+sourcesHtml(data.courses.filter(c=>c.subject===subject).flatMap(c=>c.sourceIds||[]));const rows=(f.papers||[]).map(p=>`<tr><td><strong>${esc(p.code)}</strong><br>${text(p.title||p.name||p.itemType||'')}</td><td>${p.durationMinutes?esc(p.durationMinutes)+' 分钟':esc(p.durationNote||'按当年学校通知')}</td><td>${p.marks??'—'}${p.weightPercent?`<br>权重 ${p.weightPercent}%`:''}</td><td>${text(p.description||p.structure||'')}${(p.sections||[]).map(s=>`<div>${esc(s.section)}：${esc(s.questionsOffered)} 题，作答 ${esc(s.questionsToAnswer)} 题，${esc(s.marks)} 分</div>`).join('')}</td></tr>`).join('');return `<p class="notice">以下为已核对的出版格式参考。考试日期、实作与项目安排请遵循 LP／学校当年通知。本网站的计时练习时长另列。</p>${rows?`<div class="tablewrap"><table><thead><tr><th>试卷 / 项目</th><th>参考时长</th><th>原始满分</th><th>形式</th></tr></thead><tbody>${rows}</tbody></table></div>`:''}<p>${text(f.note||f.notes||'')}</p>${sourcesHtml(f.sourceIds||[])}`;}
 function courseView(){view='subject';const n=names[subject],c=data.courses.find(c=>c.subject===subject&&c.level===level);const ps=data.papers.filter(p=>p.subject===subject);show(`<button class="btn light" data-act="home">← 全部学科</button><section class="row spread"><div><span class="eyebrow">UPPER SECONDARY</span><h1>${n[0]}</h1><p>${n[1]} · Form 4 / Form 5</p></div><div class="filters"><label>题目语言 <select id="language"><option value="both" ${language==='both'?'selected':''}>BM + English / 原文</option><option value="bm" ${language==='bm'?'selected':''}>Bahasa Melayu / 原文</option><option value="en" ${language==='en'?'selected':''}>English / 原文</option></select></label></div></section>${savedNotice()}<div class="tabs" role="tablist" aria-label="学习方式">${[['chapters','章节练习'],['papers','综合计时'],['format','官方格式参考']].map(([k,t])=>`<button role="tab" aria-selected="${tab===k}" data-tab="${k}">${t}</button>`).join('')}</div>${tab==='chapters'?`<div class="row"><label>年级 <select id="level"><option ${level==='F4'?'selected':''}>F4</option><option ${level==='F5'?'selected':''}>F5</option></select></label><p class="small">每章含选定考点与构答任务；完整学习标准仍需配合学校课程。</p></div><div class="cards">${c.chapters.map((ch,i)=>{const qc=c.questions.filter(q=>q.chapterId===ch.id).length,tc=c.tasks.filter(t=>t.chapterId===ch.id).length;return `<article class="card"><span class="badge">${level} · ${i+1}</span><h3>${text(ch.title)}</h3><p class="small">${qc} 题选择 · ${tc} 项构答 / 实作</p><button class="btn secondary" data-chapter="${esc(ch.id)}">开始本章 →</button></article>`;}).join('')}</div><details><summary>课程来源</summary>${sourcesHtml(c.sourceIds||c.chapters.flatMap(ch=>ch.sourceIds||[]))}</details>`:tab==='papers'?`<p>综合练习取材于中四、中五。先选「不限时练习」熟悉要求，再挑战「计时作答」。计时开始后，离开或刷新仍会继续。</p><div class="cards">${ps.map((p,i)=>`<article class="card"><span class="badge">SET ${i+1} · 原创短版</span><h3>${esc(n[0])}综合练习 ${i+1}</h3><p>${p.durationMinutes} 分钟 · ${p.questionIds.length} 题选择 · ${p.taskIds.length} 项构答 / 实作</p><p class="small">${text(p.reuseNotice||p.note||{zh:'与其他套题共享基础题库，部分题目重复。'})}</p><div class="row"><button class="btn" data-paper="${esc(p.id)}" data-mode="timed">计时作答</button><button class="btn secondary" data-paper="${esc(p.id)}" data-mode="study">不限时练习</button></div></article>`).join('')}</div>`:`<section class="panel"><h2>SPM ${esc(n[1])} · ${esc(data.examFormats.find(f=>f.subject===subject)?.code||'')}</h2>${formatHtml()}</section>`}`);}
 function launch({title:label,items,durationMinutes=45,mode='study',paperId=''}){const old=readSaved();if(!old&&rawSaved()&&!confirm('现有旧进度与当前题库不兼容。开始新练习会替换旧作答；需要保留时，请先下载旧进度备份。现在开始新练习？'))return;if(old&&!old.finished&&!confirm('开始新练习会替换本标签页的未完成进度。需要保留时，请先继续旧练习并下载备份。现在开始新练习？'))return;attempt={version:1,revision:data.revision,title:label,subject,items,durationMinutes,mode,paperId,started:Date.now(),index:0,responses:{},selfMarks:{},finished:false};attempt.deadline=mode==='timed'?attempt.started+durationMinutes*60000:null;persist();exam();}
 const answered=i=>i.type==='q'?Number.isInteger(attempt.responses[i.id]):Boolean(attempt.responses[i.id]?.trim());
 function timeText(){if(attempt.mode!=='timed')return '不限时练习';const s=Math.max(0,Math.ceil((attempt.deadline-Date.now())/1000));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;}
 function expire(){if(attempt&&!attempt.finished&&attempt.mode==='timed'&&Date.now()>=attempt.deadline){finish(true);return true;}return false;}
 function exam(){if(!attempt)return home();if(attempt.finished)return results();if(expire())return;view='exam';const item=attempt.items[attempt.index],q=item.type==='q'?questions.get(item.id):tasks.get(item.id),count=attempt.items.filter(answered).length;show(`<div class="exam-head"><div class="row spread"><div><strong>${esc(attempt.title)}</strong><br><span class="small">第 ${attempt.index+1} / ${attempt.items.length} 题 · 已作答 ${count}</span></div><span class="timer" id="timer" aria-label="剩余时间">${timeText()}</span><button class="btn light" data-act="leave">保存并离开</button></div><div class="progress"><i style="width:${100*count/attempt.items.length}%"></i></div></div><section class="panel"><span class="badge">${item.type==='q'?'选择题 · 1 分':'构答 / 实作 · '+q.marks+' 分（自评）'}</span><h1 style="font-size:25px">${item.type==='q'?'读题，选择最合适的答案':'写出过程与理由'}</h1><div class="question text">${text(item.type==='q'?q.stem:q.prompt)}</div>${item.type==='q'?`<div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="response" value="${i}" ${attempt.responses[item.id]===i?'checked':''}><span class="letter">${'ABCD'[i]}</span><span>${text(o)}</span></label>`).join('')}</div>`:`<label for="written" class="small">输入答案；画图、口语或实作可在纸上 / 线下完成，并在这里记录过程。不要填写个人资料。</label><textarea id="written" maxlength="12000" placeholder="写下你的推理、计算或作品说明…">${esc(attempt.responses[item.id]||'')}</textarea><p class="small">这类任务需要对照评分要点或交给老师核对。听力材料若在题干中展示，可由同伴朗读；阅读文字不能视为听力测试。</p>`}<div class="row spread"><button class="btn secondary" data-move="-1" ${attempt.index===0?'disabled':''}>上一题</button><button class="btn" ${attempt.index===attempt.items.length-1?'data-act="submit"':'data-move="1"'}>${attempt.index===attempt.items.length-1?'检查并交卷':'下一题 →'}</button></div></section><div class="dots" aria-label="题目导航">${attempt.items.map((i,n)=>`<button data-index="${n}" class="${n===attempt.index?'current ':''}${answered(i)?'answered':''}" aria-label="第${n+1}题${answered(i)?'已答':'未答'}">${n+1}</button>`).join('')}</div><div class="row"><button class="btn secondary" data-act="export">下载进度备份</button><button class="btn light" data-act="submit">提前交卷</button></div><p class="small">${attempt.mode==='timed'?'截止时间到达会自动交卷，未答题按未完成记录。':'不限时练习，可随时保存；交卷后查看解释。'}</p>`);}
 function finish(auto=false){if(!attempt||attempt.finished)return;const unanswered=attempt.items.filter(i=>!answered(i)).length;if(!auto&&!confirm(`确认交卷？${unanswered?'还有 '+unanswered+' 题未作答。':''}交卷后查看答案，原作答将锁定。`))return;attempt.finished=true;attempt.finishedAt=Date.now();attempt.autoSubmitted=auto;persist();results();if(auto)notify('计时结束，已自动交卷。');}
 function grade(){const qitems=attempt.items.filter(i=>i.type==='q');return {correct:qitems.filter(i=>attempt.responses[i.id]===questions.get(i.id).answer).length,total:qitems.length};}
 function results(){view='results';const g=grade();const ti=attempt.items.filter(i=>i.type==='t');const scored=ti.reduce((s,i)=>s+Object.values(attempt.selfMarks?.[i.id]||{}).filter(Number.isFinite).reduce((a,b)=>a+b,0),0);const max=ti.reduce((s,i)=>s+tasks.get(i.id).marks,0);show(`<button class="btn light" data-act="home">← 学习室</button><section class="panel"><span class="eyebrow">PRACTICE REVIEW</span><h1>回看你的答案</h1><p>${esc(attempt.title)} · ${attempt.autoSubmitted?'时间到，自动交卷':'已交卷'}</p><div class="row" style="gap:45px"><div class="score">${g.correct}<small> / ${g.total} 选择题</small></div><div><strong id="self-total">${scored} / ${max}</strong><br><span class="small">构答自评 · 尚未勾选按 0 记录</span></div></div><p class="small">选择题只反映本次诊断；构答分数由你对照要点填写。两者不合成为官方 SPM 分数，也不预测等级。不同有效答案可以请老师评阅。</p><div class="row"><button class="btn secondary" data-act="export">下载结果与作答</button><button class="btn light" data-act="print">打印给老师</button></div></section>${attempt.items.map((item,n)=>{const q=item.type==='q'?questions.get(item.id):tasks.get(item.id),r=attempt.responses[item.id];return `<section class="panel"><span class="badge">第 ${n+1} 题 · ${item.type==='q'?'选择题':'构答 / 实作'}</span><div class="question text">${text(item.type==='q'?q.stem:q.prompt)}</div>${item.type==='q'?`<p>你的答案：<strong>${Number.isInteger(r)?'ABCD'[r]:'未作答'}</strong> · 正确答案：<strong>${'ABCD'[q.answer]}</strong> · ${r===q.answer?'✓ 答对':'需要复习'}</p><div class="options">${q.options.map((o,i)=>`<div class="option ${i===q.answer?'correct':r===i?'incorrect':''}"><span class="letter">${'ABCD'[i]}</span><span>${text(o)}</span></div>`).join('')}</div><div class="answer"><strong>解释</strong><p>${text(q.explanation)}</p></div>`:`<h3>你的作答</h3><p class="text">${esc(r||'未填写；如已完成纸上作品，请交老师核对。')}</p><div class="answer"><h3>参考答案与评分要点</h3><p>${text(q.modelAnswer)}</p>${q.rubric.map((point,j)=>`<div class="rubric"><label for="mark-${n}-${j}">${text(point.point)}</label><select id="mark-${n}-${j}" data-mark="${esc(item.id)}" data-point="${j}" aria-label="第${n+1}题评分要点${j+1}">${Array.from({length:point.marks+1},(_,m)=>`<option value="${m}" ${(attempt.selfMarks?.[item.id]?.[j]||0)===m?'selected':''}>${m} / ${point.marks} 分</option>`).join('')}</select></div>`).join('')}</div>`}</section>`;}).join('')}`);}
 function download(){if(!attempt)return;persist();const body={...attempt};const blob=new Blob([JSON.stringify(body,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='spm-practice-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function downloadOld(){const raw=rawSaved();if(!raw)return notify('没有可下载的旧进度。');const blob=new Blob([raw],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='spm-old-progress-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function importFile(){const importActor=actor,input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;if(f.size>3000000)return notify('备份过大，无法导入。');try{const a=JSON.parse(await f.text());if(actor!==importActor)return notify('账号已切换，请重新选择要导入的备份。');if(!valid(a))throw Error('备份格式或题库版本不匹配，请保留原文件。');if(rawSaved()&&!confirm(readSaved()?'导入会替换本标签页的练习。继续？':'导入会替换不兼容的旧作答；需要保留时，请先下载旧进度备份。继续导入？'))return;attempt=a;attempt.selfMarks=cleanMarks(a.selfMarks);persist();exam();}catch(e){notify(e.message||'无法读取备份。');}};input.click();}
 function cleanMarks(raw){const out={};for(const [id,values]of Object.entries(raw||{})){const t=tasks.get(id);if(!t||!values||typeof values!=='object')continue;out[id]={};t.rubric.forEach((p,j)=>{const n=values[j];if(Number.isInteger(n)&&n>=0&&n<=p.marks)out[id][j]=n;});}return out;}
 app.addEventListener('click',e=>{if(!ready)return;const b=e.target.closest('button');if(!b)return;if(b.dataset.subject){subject=b.dataset.subject;tab='chapters';return courseView();}if(b.dataset.tab){tab=b.dataset.tab;return courseView();}if(b.dataset.chapter){const ch=chapters.get(b.dataset.chapter),c=data.courses.find(c=>c.chapters.some(t=>t.id===ch.id));return launch({title:names[c.subject][0]+' · '+c.level+' · '+title(ch.title),items:[...c.questions.filter(q=>q.chapterId===ch.id).map(q=>({type:'q',id:q.id})),...c.tasks.filter(t=>t.chapterId===ch.id).map(t=>({type:'t',id:t.id}))],mode:'study'});}if(b.dataset.paper){const p=data.papers.find(p=>p.id===b.dataset.paper);return launch({title:title(p.title),items:[...p.questionIds.map(id=>({type:'q',id})),...p.taskIds.map(id=>({type:'t',id}))],durationMinutes:p.durationMinutes,mode:b.dataset.mode,paperId:p.id});}if(b.dataset.move||b.dataset.index!==undefined){if(expire())return;attempt.index=b.dataset.index!==undefined?Number(b.dataset.index):attempt.index+Number(b.dataset.move);persist();return exam();}const a=b.dataset.act;if(a==='home'){persist();return home();}if(a==='resume'){attempt=readSaved();if(attempt)attempt.selfMarks=cleanMarks(attempt.selfMarks);return exam();}if(a==='leave'){persist();return home();}if(a==='submit')return finish(expire());if(a==='export')return download();if(a==='export-old')return downloadOld();if(a==='import')return importFile();if(a==='print')return window.print();});
 app.addEventListener('change',e=>{if(e.target.id==='language'){language=e.target.value;return courseView();}if(e.target.id==='level'){level=e.target.value;return courseView();}if(e.target.name==='response'){if(!attempt||attempt.finished||expire())return;attempt.responses[attempt.items[attempt.index].id]=Number(e.target.value);persist();}if(e.target.dataset.mark&&attempt?.finished){const id=e.target.dataset.mark,j=Number(e.target.dataset.point),n=Number(e.target.value),p=tasks.get(id)?.rubric[j];if(!p||!Number.isInteger(n)||n<0||n>p.marks)return;attempt.selfMarks??={};attempt.selfMarks[id]??={};attempt.selfMarks[id][j]=n;persist();const ti=attempt.items.filter(i=>i.type==='t'),score=ti.reduce((s,i)=>s+Object.values(attempt.selfMarks[i.id]||{}).reduce((a,b)=>a+b,0),0),max=ti.reduce((s,i)=>s+tasks.get(i.id).marks,0);$('self-total').textContent=`${score} / ${max}`;}});
 app.addEventListener('input',e=>{if(e.target.id==='written'&&attempt&&!attempt.finished&&!expire()){attempt.responses[attempt.items[attempt.index].id]=e.target.value.slice(0,12000);persist();}});
 setInterval(()=>{if(attempt&&!attempt.finished&&view==='exam'){if(!expire()&&$('timer'))$('timer').textContent=timeText();}},1000);
 window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden)persist();else if(view==='exam')expire();});
 async function init(){try{const r=await fetch('./spm-data.json?v=e48c3c70d2b1535a');if(!r.ok)throw Error('课程暂时无法载入，请稍后重试。');data=await r.json();data.courses.forEach(c=>{c.questions.forEach(q=>questions.set(q.id,q));c.tasks.forEach(t=>tasks.set(t.id,t));c.chapters.forEach(ch=>chapters.set(ch.id,ch));});const config=window.WQ_CONFIG||{};if(window.supabase&&config.supabaseUrl&&config.supabasePublishableKey){const db=window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data:auth}=await db.auth.getSession();actor=auth.session?.user?.id||'guest';db.auth.onAuthStateChange((event,s)=>{const next=s?.user?.id||'guest';if(next!==actor){attempt=null;actor=next;if(ready)home();}});}ready=true;home();}catch(e){show(`<section class="panel"><h1>暂时无法打开学习室</h1><p>${esc(e.message)}</p><button class="btn" onclick="location.reload()">重新载入</button><a class="btn light" href="./index.html">返回学科地图</a></section>`);}}
 init();
})();
